export interface User {
    id: string,
    token?: string,
    phone: string,
    speciality?: string,
    address?: string,
    licenseNumber?: number,
    lastname?: string,
    firstname?: string,
    gender?: string,
    city?: string,
    attachments?: string[],
    email?: string,
    emergencyContact?: string,
    dateOfBirth?: string,
    dateOfGraduation?: string,
    earnings?: number,
    isRegistrationComplete: boolean,
    isVerified: boolean,
    role: string,
    profileImage?: string,
    createdAt: string,
    updatedAt: string,
}
